# Generated by Django 3.1.6 on 2021-03-16 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_almacenpokemon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='almacenpokemon',
            old_name='id_pokemon',
            new_name='pokemon',
        ),
        migrations.RemoveField(
            model_name='almacenpokemon',
            name='id_usuario',
        ),
        migrations.AddField(
            model_name='almacenpokemon',
            name='nick_name',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AlmacenPokemonCapturado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(max_length=20)),
                ('is_party_member', models.BooleanField(default=False)),
                ('specie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.pokemon')),
            ],
        ),
    ]
